In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("glass.csv")
data

RI     Na    Mg    Al     Si     K    Ca    Ba    Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00     1
5    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26     1
6    1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.00  0.00     1
7    1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.00  0.00     1
8    1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.00  0.00     1
9    1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.00  0.11     1
10   1.51571  12.72  3.46  1.56  73.20  0.67  8.09  0.00  0.24     1
11   1.51763  12.80  3.66  1.27  73.01  0.60  8.56  0.00  0.00     1
12   1.51589  12.88  3.43  1.40  73.28  0.69  8.05  0.00  0.24     1
13   1.51748  12.86  3.56  1.27  73.21  0.54  8.38  0.00  0.17     1
14   1.51763  12.61  3.59  1.31  73.29  0.58  8.50  0.00  0.00     1
15   1.51761  12.81  3.54  1.23  73.24  0.58  8.39  0.00  0.00     1
16   1.51784  12.68  3.67  1.16  73.11  0.61  8.70  0.00  0.00     1
17   1.52196  14.36  3.85  0.89  71.36  0.15  9.15  0.00  0.00     1
18   1.51911  13.90  3.73  1.18  72.12  0.06  8.89  0.00  0.00     1
19   1.51735  13.02  3.54  1.69  72.73  0.54  8.44  0.00  0.07     1
20   1.51750  12.82  3.55  1.49  72.75  0.54  8.52  0.00  0.19     1
21   1.51966  14.77  3.75  0.29  72.02  0.03  9.00  0.00  0.00     1
22   1.51736  12.78  3.62  1.29  72.79  0.59  8.70  0.00  0.00     1
23   1.51751  12.81  3.57  1.35  73.02  0.62  8.59  0.00  0.00     1
24   1.51720  13.38  3.50  1.15  72.85  0.50  8.43  0.00  0.00     1
25   1.51764  12.98  3.54  1.21  73.00  0.65  8.53  0.00  0.00     1
26   1.51793  13.21  3.48  1.41  72.64  0.59  8.43  0.00  0.00     1
27   1.51721  12.87  3.48  1.33  73.04  0.56  8.43  0.00  0.00     1
28   1.51768  12.56  3.52  1.43  73.15  0.57  8.54  0.00  0.00     1
29   1.51784  13.08  3.49  1.28  72.86  0.60  8.49  0.00  0.00     1
..       ...    ...   ...   ...    ...   ...   ...   ...   ...   ...
184  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.00     6
185  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19  0.00     7
186  1.51838  14.32  3.26  2.22  71.25  1.46  5.79  1.63  0.00     7
187  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00  0.00     7
188  1.52247  14.86  2.20  2.06  70.26  0.76  9.76  0.00  0.00     7
189  1.52365  15.79  1.83  1.31  70.43  0.31  8.61  1.68  0.00     7
190  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76  0.00     7
191  1.51602  14.85  0.00  2.38  73.28  0.00  8.76  0.64  0.09     7
192  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.40  0.09     7
193  1.51719  14.75  0.00  2.00  73.02  0.00  8.53  1.59  0.08     7
194  1.51683  14.56  0.00  1.98  73.29  0.00  8.52  1.57  0.07     7
195  1.51545  14.14  0.00  2.68  73.39  0.08  9.07  0.61  0.05     7
196  1.51556  13.87  0.00  2.54  73.23  0.14  9.41  0.81  0.01     7
197  1.51727  14.70  0.00  2.34  73.28  0.00  8.95  0.66  0.00     7
198  1.51531  14.38  0.00  2.66  73.10  0.04  9.08  0.64  0.00     7
199  1.51609  15.01  0.00  2.51  73.05  0.05  8.83  0.53  0.00     7
200  1.51508  15.15  0.00  2.25  73.50  0.00  8.34  0.63  0.00     7
201  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00  0.00     7
202  1.51514  14.85  0.00  2.42  73.72  0.00  8.39  0.56  0.00     7
203  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71  0.00     7
204  1.51617  14.95  0.00  2.27  73.30  0.00  8.71  0.67  0.00     7
205  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55  0.00     7
206  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.00     7
207  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.00     7
208  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.00     7
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00     7
210  1.5

In [3]:
X=data[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']].values
Y=data[['Type']].values

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.50,random_state=1)

In [5]:
from sklearn.naive_bayes import GaussianNB

In [6]:
gnb=GaussianNB()
gnb.fit(X_train,Y_train)
y_pred=gnb.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
y_pred

array([2, 7, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 5, 3, 3, 6, 3, 3, 7,
       2, 3, 3, 3, 3, 3, 3, 3, 2, 6, 3, 3, 3, 2, 3, 3, 2, 3, 3, 7, 7, 3,
       7, 3, 3, 3, 3, 7, 3, 3, 2, 3, 2, 3, 7, 3, 5, 7, 3, 2, 3, 3, 3, 3,
       5, 3, 7, 2, 3, 2, 5, 3, 3, 3, 3, 3, 3, 7, 7, 3, 5, 3, 7, 3, 2, 2,
       3, 5, 2, 6, 7, 3, 6, 3, 7, 3, 2, 3, 3, 7, 7, 3, 7, 3, 7],
      dtype=int64)

In [8]:
X_test

array([[1.52222e+00, 1.44300e+01, 0.00000e+00, 1.00000e+00, 7.26700e+01,
        1.00000e-01, 1.15200e+01, 0.00000e+00, 8.00000e-02],
       [1.51645e+00, 1.49400e+01, 0.00000e+00, 1.87000e+00, 7.31100e+01,
        0.00000e+00, 8.67000e+00, 1.38000e+00, 0.00000e+00],
       [1.53125e+00, 1.07300e+01, 0.00000e+00, 2.10000e+00, 6.98100e+01,
        5.80000e-01, 1.33000e+01, 3.15000e+00, 2.80000e-01],
       [1.53393e+00, 1.23000e+01, 0.00000e+00, 1.00000e+00, 7.01600e+01,
        1.20000e-01, 1.61900e+01, 0.00000e+00, 2.40000e-01],
       [1.51926e+00, 1.32000e+01, 3.33000e+00, 1.28000e+00, 7.23600e+01,
        6.00000e-01, 9.14000e+00, 0.00000e+00, 1.10000e-01],
       [1.51753e+00, 1.25700e+01, 3.47000e+00, 1.38000e+00, 7.33900e+01,
        6.00000e-01, 8.55000e+00, 0.00000e+00, 6.00000e-02],
       [1.51754e+00, 1.33900e+01, 3.66000e+00, 1.19000e+00, 7.27900e+01,
        5.70000e-01, 8.27000e+00, 0.00000e+00, 1.10000e-01],
       [1.51779e+00, 1.36400e+01, 3.65000e+00, 6.50000e-01, 7.

In [9]:
gnb.predict([[1.51514,14.85,0.00,2.42,73.72,0.00,8.39,0.56,0.00]])

array([7], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score

In [16]:
accuracy=accuracy_score(Y_test,y_pred)

In [17]:
print(accuracy)

0.34579439252336447


## by using logistic regression

In [37]:
df=pd.read_csv("glass.csv")
df

RI     Na    Mg    Al     Si     K    Ca    Ba    Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00     1
5    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26     1
6    1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.00  0.00     1
7    1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.00  0.00     1
8    1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.00  0.00     1
9    1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.00  0.11     1
10   1.51571  12.72  3.46  1.56  73.20  0.67  8.09  0.00  0.24     1
11   1.51763  12.80  3.66  1.27  73.01  0.60  8.56  0.00  0.00     1
12   1.51589  12.88  3.43  1.40  73.28  0.69  8.05  0.00  0.24     1
13   1.51748  12.86  3.56  1.27  73.21  0.54  8.38  0.00  0.17     1
14   1.51763  12.61  3.59  1.31  73.29  0.58  8.50  0.00  0.00     1
15   1.51761  12.81  3.54  1.23  73.24  0.58  8.39  0.00  0.00     1
16   1.51784  12.68  3.67  1.16  73.11  0.61  8.70  0.00  0.00     1
17   1.52196  14.36  3.85  0.89  71.36  0.15  9.15  0.00  0.00     1
18   1.51911  13.90  3.73  1.18  72.12  0.06  8.89  0.00  0.00     1
19   1.51735  13.02  3.54  1.69  72.73  0.54  8.44  0.00  0.07     1
20   1.51750  12.82  3.55  1.49  72.75  0.54  8.52  0.00  0.19     1
21   1.51966  14.77  3.75  0.29  72.02  0.03  9.00  0.00  0.00     1
22   1.51736  12.78  3.62  1.29  72.79  0.59  8.70  0.00  0.00     1
23   1.51751  12.81  3.57  1.35  73.02  0.62  8.59  0.00  0.00     1
24   1.51720  13.38  3.50  1.15  72.85  0.50  8.43  0.00  0.00     1
25   1.51764  12.98  3.54  1.21  73.00  0.65  8.53  0.00  0.00     1
26   1.51793  13.21  3.48  1.41  72.64  0.59  8.43  0.00  0.00     1
27   1.51721  12.87  3.48  1.33  73.04  0.56  8.43  0.00  0.00     1
28   1.51768  12.56  3.52  1.43  73.15  0.57  8.54  0.00  0.00     1
29   1.51784  13.08  3.49  1.28  72.86  0.60  8.49  0.00  0.00     1
..       ...    ...   ...   ...    ...   ...   ...   ...   ...   ...
184  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.00     6
185  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19  0.00     7
186  1.51838  14.32  3.26  2.22  71.25  1.46  5.79  1.63  0.00     7
187  1.52315  13.44  3.34  1.23  72.38  0.60  8.83  0.00  0.00     7
188  1.52247  14.86  2.20  2.06  70.26  0.76  9.76  0.00  0.00     7
189  1.52365  15.79  1.83  1.31  70.43  0.31  8.61  1.68  0.00     7
190  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76  0.00     7
191  1.51602  14.85  0.00  2.38  73.28  0.00  8.76  0.64  0.09     7
192  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.40  0.09     7
193  1.51719  14.75  0.00  2.00  73.02  0.00  8.53  1.59  0.08     7
194  1.51683  14.56  0.00  1.98  73.29  0.00  8.52  1.57  0.07     7
195  1.51545  14.14  0.00  2.68  73.39  0.08  9.07  0.61  0.05     7
196  1.51556  13.87  0.00  2.54  73.23  0.14  9.41  0.81  0.01     7
197  1.51727  14.70  0.00  2.34  73.28  0.00  8.95  0.66  0.00     7
198  1.51531  14.38  0.00  2.66  73.10  0.04  9.08  0.64  0.00     7
199  1.51609  15.01  0.00  2.51  73.05  0.05  8.83  0.53  0.00     7
200  1.51508  15.15  0.00  2.25  73.50  0.00  8.34  0.63  0.00     7
201  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00  0.00     7
202  1.51514  14.85  0.00  2.42  73.72  0.00  8.39  0.56  0.00     7
203  1.51658  14.80  0.00  1.99  73.11  0.00  8.28  1.71  0.00     7
204  1.51617  14.95  0.00  2.27  73.30  0.00  8.71  0.67  0.00     7
205  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55  0.00     7
206  1.51645  14.94  0.00  1.87  73.11  0.00  8.67  1.38  0.00     7
207  1.51831  14.39  0.00  1.82  72.86  1.41  6.47  2.88  0.00     7
208  1.51640  14.37  0.00  2.74  72.85  0.00  9.45  0.54  0.00     7
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00     7
210  1.5

In [38]:
df.shape

(214, 10)

In [39]:
df.index

RangeIndex(start=0, stop=214, step=1)

In [40]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

In [41]:
df.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516523   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [42]:
data.isnull().sum().sum()

0

In [43]:
X=data.iloc[:,0:-1]
Y=data.iloc[:,-1]

In [44]:
X.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=1)

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
log_reg2=LogisticRegression()
log_reg2.fit(X_train,Y_train)
y_pred=log_reg2.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [49]:
log_reg2.predict([[1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0]])

array([1], dtype=int64)

In [50]:
log_reg2.predict([[1.51640,14.37,0.00,2.74,72.85,0.00,9.45,0.54,0.00]])

array([7], dtype=int64)